[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
core   = { path = "../core" }
loader = { path = "../crates/loader" }
render = { package = "sailfish-render", path = "../crates/sailfish-render" }
anyhow = "1"